### ISSUE TITLE
This is where the download will fetch from. Ill just make it identical to the normal repo

### ISSUE THREAD

**Issue by dinguschan-owo** [dinguschan-owo/DingusProxy-Offline#1]
@Project516

**Comment by Project516** [comment]
how bout it fetches from the website itself?

**Comment by dinguschan-owo** [comment]
> how bout it fetches from the website itself?

then I would need to pretty much remake DingusProxy inside DingusProxy. websites don't like having their content fetched by bots (js), so they block it. the easy way to get around this you can use CORS proxies to scrape and return the website, which is just what DingusProxy does (then rebuilds it and tweaks some stuff to fit). In other words, you need a proxy in the proxy to fetch from itself

**Comment by Project516** [comment]
oh

**Comment by Project516** [comment]
wait just redirect to website.com/downloadfolder/file.html and tell the user to ctrl s

**Comment by Project516** [comment]
the file has the js and css combined

**Comment by Project516** [comment]
https://stackoverflow.com/questions/44730201/it-it-possible-to-use-javascript-to-save-a-file-to-same-directory-as-current-fil

**Comment by dinguschan-owo** [comment]
> wait just redirect to website.com/downloadfolder/file.html and tell the user to ctrl s

I would need a GitHub subdomain, but I'm too broke for that. Ctrl s on the regular site or "https://site.com/index.html" will save as an .mhtml, which is a snapshot cache or the site or literally just an interactive screenshot. The fetching works fine, so I think for now I will leave it as is

**Comment by Project516** [comment]
check pull request

**Comment by dinguschan-owo** [comment]
this "fetch('/d0wnload/la-essay.txt.html')" will only work for you, because "la-essay.txt.html" is a loca lfile on your computer. same as when I tried to fetch from "https://raw.githubusercontent.com/dinguschan-owo/DingusProxy-Offline/main/%F0%9D%99%B3%F0%9D%9A%92%F0%9D%9A%97%F0%9D%9A%90%F0%9D%9A%9E%F0%9D%9A%9C%F0%9D%99%BF%F0%9D%9A%9B%F0%9D%9A%98%F0%9D%9A%A1%F0%9D%9A%A2%F0%9D%99%BE%F0%9D%9A%8F%F0%9D%9A%8F%F0%9D%9A%95%F0%9D%9A%92%F0%9D%9A%97%F0%9D%9A%8E.html?token=GHSAT0AAAAAACUS64YWPBKJFUK45ZMNMWA2ZVSY75Q" both of these do not work, because it only works for the user that has the token/file.

**Comment by Project516** [comment]
oh

**Comment by dinguschan-owo** [comment]
All good, it is a good idea tho. leave a issue on the main page and I'll look into after I fix rendering files :D
